theme: jekyll-theme-hacker
title: root💀n16hth4wk-sec:~#
description: Recon → Enumerate → Exploit → Repeat!. 💀
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap
